import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "../../components/SessionWrapper";
import { ThemeProvider } from "../../components/theme-provider";
import DefaultLayout from "../../components/DefaultLayout";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider>
            <Toaster />
            <DefaultLayout>
              {children}
            </DefaultLayout>
          </ThemeProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
